Repository mosaic-design-system/docs, pull requests merged in 2022-05, with the labels that each got.

#104 Update Component “tabs”
  src/components/tabs.md
Labels: netlify-cms/pending_review

#89 Update Forms “textarea”
  src/forms/textarea.md
Labels: netlify-cms/pending_review

#96 Update Component “pagination”
  src/components/pagination.md
Labels: netlify-cms/pending_review

#69 Update Component “breadcrumb”
  src/components/breadcrumb.md
Labels: netlify-cms/pending_review

#118 Update Component “treeview”
  src/components/treeview.md
Labels: netlify-cms/pending_review

#119 Update Component “tile”
  src/components/tile.md
Labels: netlify-cms/pending_review

#91 Update Component “list-group”
  src/components/list-group.md
Labels: netlify-cms/pending_review

#50 Update Component “tooltip”
  src/components/tooltip.md
Labels: netlify-cms/pending_review

#94 Create Component “selector”
  src/components/selector.md
Labels: netlify-cms/pending_review

#81 Update Component “alert”
  src/components/alert.md
Labels: netlify-cms/pending_review

#75 Update Component “page-header”
  src/components/page-header.md
Labels: netlify-cms/pending_review

#101 Update Component “timeline”
  src/components/timeline.md
Labels: netlify-cms/pending_review

#106 Update Component “nav”
  src/components/nav.md
Labels: netlify-cms/pending_review

#48 Update Component “progress-bar”
  src/components/progress-bar.md
Labels: netlify-cms/pending_review

#103 Update Component “placeholder”
  src/components/placeholder.md
Labels: netlify-cms/pending_review

#74 Create Guideline “system-messaging”
  src/guidelines/system-messaging.md
Labels: netlify-cms/pending_review

#78 Create Component “navigation-rail”
  src/components/navigation-rail.md
Labels: netlify-cms/pending_review

#90 Create Guideline “accessibility”
  src/assets/img/colour-perception-images.png
  src/guidelines/accessibility.md
Labels: netlify-cms/pending_review

#68 Create Guideline “icons-1”
  src/assets/img/home-colour32.svg
  src/assets/img/home-office-colour32.svg
  src/assets/img/home-office32.svg
  src/assets/img/home16.svg
  src/assets/img/home24.svg
  src/assets/img/home32.svg
  src/assets/img/home48.svg
  src/assets/img/home64.svg
  src/assets/img/inspection-colour32.svg
  src/assets/img/inspection32.svg
  src/assets/img/online-store-colour32.svg
  src/assets/img/online-store32.svg
  src/assets/img/star-colour32.svg
  src/assets/img/star32.svg
  src/assets/img/thumbnails-colour32.svg
  src/assets/img/thumbnails32.svg
  src/guidelines/icons-1.md
Labels: netlify-cms/pending_review

#77 Create Component “navigation-bar”
  src/components/navigation-bar.md
Labels: netlify-cms/pending_review

#122 Update Team “ian-hill”
  src/team/ian-hill.md
Labels: netlify-cms/pending_publish

#76 Create Component “navigation-header”
  src/components/navigation-header.md
Labels: netlify-cms/pending_review

#37 Update Team “james-cavanagh”
  src/team/james-cavanagh.md
Labels: netlify-cms/pending_review

#98 Update Guideline “brand”
  src/guidelines/brand.md
Labels: netlify-cms/draft

#123 Update Guideline “brand”
  src/guidelines/brand.md
Labels: netlify-cms/draft

#124 Update Guideline “brand”
  src/guidelines/brand.md
Labels: netlify-cms/draft

#115 Update Guideline “overview”
  src/assets/img/downloading.svg
  src/guidelines/overview.md
Labels: netlify-cms/pending_publish

#56 Update Component “button”
  src/components/button.md
Labels: netlify-cms/pending_review

#121 Update Component “chip”
  src/components/chip.md
Labels: netlify-cms/pending_review

#120 Update Forms “radio”
  src/forms/radio.md
Labels: netlify-cms/pending_review

#97 Update Component “drawer”
  src/components/drawer.md
Labels: netlify-cms/pending_review

#92 Create Component “table”
  src/components/table.md
Labels: netlify-cms/pending_review

#109 Update Component “card”
  src/components/card.md
Labels: netlify-cms/pending_review

#116 Create Component “toggle”
  src/components/toggle.md
Labels: netlify-cms/pending_review

#58 Update Forms “select”
  src/forms/select.md
Labels: netlify-cms/pending_review

#117 Create Component “validation”
  src/components/validation.md
Labels: netlify-cms/pending_review

#57 Update Component “snackbar”
  src/components/snackbar.md
Labels: netlify-cms/pending_review

#47 Create Component “ratings”
  src/components/ratings.md
Labels: netlify-cms/pending_review

#130 Update Team “louise-foster”
  src/team/louise-foster.md
Labels: netlify-cms/draft

#133 Update Guideline “overview”
  src/guidelines/overview.md
Labels: netlify-cms/draft

#137 Update Designing “our-design-kit”
  src/designing/our-design-kit.md
Labels: netlify-cms/draft

#138 Update In App Guidance “overview”
  src/in-app-guidance/overview.md
Labels: netlify-cms/draft

#139 Update Pattern “overview”
  src/patterns/overview.md
Labels: netlify-cms/draft

#140 Create Guideline “user-research”
  src/guidelines/user-research.md
Labels: netlify-cms/draft

#143 Update Guideline “style-guide”
  src/guidelines/style-guide.md
Labels: netlify-cms/draft

#142 Update Guideline “tone-of-voice”
  src/guidelines/tone-of-voice.md
Labels: netlify-cms/draft

#141 Update Guideline “system-messaging”
  src/guidelines/system-messaging.md
Labels: netlify-cms/draft

#144 Update Component “accordion”
  src/components/accordion.md
Labels: netlify-cms/draft

#145 Update Component “alert”
  src/components/alert.md
Labels: netlify-cms/draft

#147 Update Component “alert”
  src/components/alert.md
Labels: netlify-cms/draft

#146 Update Component “avatar”
  src/components/avatar.md
Labels: netlify-cms/draft

#148 Update Component “back-to-top”
  src/components/back-to-top.md
Labels: netlify-cms/draft

#150 Update Component “button-group”
  src/components/button-group.md
Labels: netlify-cms/draft

#149 Update Component “breadcrumb”
  src/components/breadcrumb.md
Labels: netlify-cms/draft

#151 Update Component “button”
  src/components/button.md
Labels: netlify-cms/draft

#152 Update Component “card”
  src/components/card.md
Labels: netlify-cms/draft

#156 Update Component “dropdown”
  src/components/dropdown.md
Labels: netlify-cms/draft

#153 Update Component “chip”
  src/components/chip.md
Labels: netlify-cms/draft

#154 Update Component “dialog”
  src/components/dialog.md
Labels: netlify-cms/draft

#155 Update Component “drawer”
  src/components/drawer.md
Labels: netlify-cms/draft

#157 Update Component “list-group”
  src/components/list-group.md
Labels: netlify-cms/draft

#158 Update Component “map”
  src/components/map.md
Labels: netlify-cms/draft

#163 Create Guideline “mobile”
  src/guidelines/mobile.md
Labels: netlify-cms/draft

#159 Update Component “nav”
  src/components/nav.md
Labels: netlify-cms/draft

#160 Update Component “navigation-rail”
  src/components/navigation-rail.md
Labels: netlify-cms/draft

#161 Update Component “page-header”
  src/components/page-header.md
Labels: netlify-cms/draft

#162 Update Component “accordion”
  src/components/accordion.md
Labels: netlify-cms/draft

#165 Update Component “pagination”
  src/components/pagination.md
Labels: netlify-cms/draft

#164 Update Component “drawer”
  src/components/drawer.md
Labels: netlify-cms/draft

#166 Update Component “placeholder”
  src/components/placeholder.md
Labels: netlify-cms/draft

#167 Update Component “popover”
  src/components/popover.md
Labels: netlify-cms/draft

#168 Update Component “ratings”
  src/components/ratings.md
Labels: netlify-cms/draft

#169 Update Component “selector”
  src/components/selector.md
Labels: netlify-cms/draft

#170 Update Component “snackbar”
  src/components/snackbar.md
Labels: netlify-cms/draft

#171 Update Component “spinner”
  src/components/spinner.md
Labels: netlify-cms/draft

#172 Create Pattern “table”
  src/patterns/table.md
Labels: netlify-cms/draft

#173 Update Component “table”
  src/components/table.md
Labels: netlify-cms/draft

#174 Update Component “tabs”
  src/components/tabs.md
Labels: netlify-cms/draft

#175 Update Component “tile”
  src/components/tile.md
Labels: netlify-cms/draft

#93 Create Forms “rich-text-editor”
  src/forms/rich-text-editor.md
Labels: netlify-cms/pending_review

#100 Update Forms “checkbox”
  src/forms/checkbox.md
Labels: netlify-cms/pending_review

#182 Create Guideline “field-affordance”
  src/guidelines/field-affordance.md
Labels: netlify-cms/draft

#183 Update Forms “textarea”
  src/forms/textarea.md
Labels: netlify-cms/draft

#176 Update Component “toggle”
  src/components/toggle.md
Labels: netlify-cms/draft

#177 Update Component “validation”
  src/components/validation.md
Labels: netlify-cms/draft

#178 Update Forms “overview”
  src/forms/overview.md
Labels: netlify-cms/draft

#179 Update Forms “picklist”
  src/forms/picklist.md
Labels: netlify-cms/draft

#180 Update Forms “radio”
  src/forms/radio.md
Labels: netlify-cms/draft

#181 Update Forms “select”
  src/forms/select.md
Labels: netlify-cms/draft

#184 Update Forms “checkbox”
  src/forms/checkbox.md
Labels: netlify-cms/pending_review

#186 Update Forms “rich-text-editor”
  src/forms/rich-text-editor.md
Labels: netlify-cms/draft

#191 Update Forms “picklist”
  src/forms/picklist.md
Labels: netlify-cms/draft

#187 Update Component “ratings”
  src/components/ratings.md
Labels: netlify-cms/draft

#188 Update Component “selector”
  src/components/selector.md
Labels: netlify-cms/draft

#189 Update Component “table”
  src/components/table.md
Labels: netlify-cms/draft

#190 Update Forms “input-groups”
  src/forms/input-groups.md
Labels: netlify-cms/draft

#192 Update Forms “rich-text-editor”
  src/forms/rich-text-editor.md
Labels: netlify-cms/draft

#129 Update Team “jonathan-smith”
  src/team/jonathan-smith.md
Labels: netlify-cms/pending_review

#193 Update Team “louise-foster”
  src/team/louise-foster.md
Labels: netlify-cms/draft

#128 Update Team “amie-wilson”
  src/team/amie-wilson.md
Labels: netlify-cms/pending_review

#194 Update Team “jonathan-smith”
  src/team/jonathan-smith.md
Labels: netlify-cms/draft

#185 Update Forms “checkbox”
  src/forms/checkbox.md
Labels: netlify-cms/pending_review

#114 Update Forms “input”
  src/forms/input.md
Labels: netlify-cms/pending_review

#199 Update Team “amie-wilson”
  src/team/amie-wilson.md
Labels: netlify-cms/pending_review

#131 Update Team “rike-catalani”
  src/team/rike-catalani.md
Labels: netlify-cms/pending_review

#195 Update Component “table”
  src/components/table.md
Labels: netlify-cms/draft

#213 Create Forms “validation”
  src/forms/validation.md
Labels: netlify-cms/draft

#210 Update Team “louise-foster”
  src/team/louise-foster.md
Labels: netlify-cms/draft

#135 Create Team “aaron-lowe”
  src/team/aaron-lowe.md
Labels: netlify-cms/pending_publish

#214 Create Forms “toggle”
  src/forms/toggle.md
Labels: netlify-cms/draft

#216 Update Mosaic “what-is-mosaic”
  src/mosaic/what-is-mosaic.md
Labels: netlify-cms/pending_publish

#222 Update Team “ian-hill”
  src/team/ian-hill.md
Labels: netlify-cms/draft

#223 Update Team “geoff-friers”
  src/team/geoff-friers.md
Labels: netlify-cms/draft

#224 Update Team “dan-hitchins”
  src/team/dan-hitchins.md
Labels: netlify-cms/draft

#230 Update Designing “get-started”
  src/assets/img/downloading-small.svg
  src/designing/get-started.md
Labels: netlify-cms/pending_review

#234 Update Team “geoff-faiers”
  src/team/geoff-faiers.md
Labels: netlify-cms/pending_publish

#196 Update Guideline “colour”
  src/assets/img/danger-light.png
  src/assets/img/fonts-light.png
  src/assets/img/greyscale-light.png
  src/assets/img/info-light.png
  src/assets/img/links-light.png
  src/assets/img/primary-light.png
  src/assets/img/success-light.png
  src/assets/img/warning-light.png
  src/guidelines/colour.md
Labels: netlify-cms/pending_review

#227 Update Mosaic “ux-strategy-at-advanced”
  src/mosaic/ux-strategy-at-advanced.md
Labels: netlify-cms/draft

#197 Update Designing “our-design-kit”
  src/designing/our-design-kit.md
Labels: netlify-cms/draft

#240 Update Guideline “accessibility”
  src/guidelines/accessibility.md
Labels: netlify-cms/pending_review

#243 Update Team “ian-hill”
  src/team/ian-hill.md
Labels: netlify-cms/pending_publish
